### ISSUE TITLE
I do not understand (chromeOS)

### ISSUE THREAD

**Issue by AVRForVR** [hadcl4/Thunder#7]
Hey, I don't get what it means to install nano and how to finish installing thunder
 or which terminal to use it in, the one I downloaded or the ChromeOS one?
![Screenshot 2024-03-15 1 33 40 PM](https://github.com/hadcl4/Thunder/assets/163577351/6c10aae1-9c78-4385-803e-2b46d3f71aed)
![Screenshot 2024-03-15 1 34 12 PM](https://github.com/hadcl4/Thunder/assets/163577351/a2adebfc-259d-4bfb-af09-d7bdfb1bea1a)

**Comment by AVRForVR** [comment]
WRONG LINE READ! I need to know how to update it and install nano, after that thunder

**Comment by hadcl4** [comment]
> WRONG LINE READ! I need to know how to update it and install nano, after that thunder

Hello, @AVRForVR! Sorry for not seeing your issue sooner!

To install Thunder on ChromeOS, I'm pretty sure what you need to do is first install nano (run `sudo apt install nano`, although this step MIGHT be unnecessary now on newer versions of Debian (by that I mean Bullseye), I've only installed Thunder on chromeOS in Debian Buster), and then also "gnome-terminal" (should be something like `sudo apt install gnome-terminal`). After that, run `sudo nano /usr/bin/x-terminal-emulator` and make the file look like this: 
![image](https://github.com/hadcl4/Thunder/assets/101465265/65371e16-5190-4d01-9c72-246b28c97458)
Make sure the one line with "garcon" has the `#`.

Then after that, run `cd ~; git clone https://github.com/hadcl4/Thunder`, though you might first need to install `git` with `sudo apt install git`. Lastly, run `cd Thunder && chmod +x setup && ./setup`.

If you have any trouble, let me know and I'll try my best to help out! Just something to know is that I haven't installed Thunder on chromeOS in maybe about 2 years now, so I might've forgot some things...

**Comment by hadcl4** [comment]
> Hey, I don't get what it means to install nano and how to finish installing thunder or which terminal to use it in, the one I downloaded or the ChromeOS one? ![Screenshot 2024-03-15 1 33 40 PM](https://private-user-
Also, for which terminal to use, you can continue using the ChromeOS one, it doesn't matter which terminal you use.

**Comment by AVRForVR** [comment]
Thank you, I just realized you commented
