### ISSUE TITLE
Infinite loading icon

### ISSUE THREAD

**Issue by AVRForVR** [hadcl4/Thunder#8]
does not want to launch

**Comment by hadcl4** [comment]
Would you please give more information? Try running `thunder-cli --gui` in a terminal, and paste the output here.

**Comment by AVRForVR** [comment]
![Screenshot 2024-03-23 5 46 38 PM](https://github.com/hadcl4/Thunder/assets/163577351/41e7c5cf-2bc3-4682-93f4-af2d9d774979)

**Comment by AVRForVR** [comment]
so it does a infinite load on taskbar, and does not open the window, and your command prompt for me to run does not work

**Comment by AVRForVR** [comment]
![Screenshot 2024-03-23 5 51 35 PM](https://github.com/hadcl4/Thunder/assets/163577351/3e495822-5cf3-4952-bce1-3545e37c291f)

**Comment by hadcl4** [comment]
This should be a pretty simple fix... Seems I forgot to include instructions to install `guizero`...

Well, first you'll need to install `pip3`. You can do this by running `sudo apt install python3-pip`. Then after that's installed, run `pip3 install guizero`. If that second command doesn't work, try `sudo pip3 install guizero` instead.

**Comment by hadcl4** [comment]
Also, you might also need to install `pillow` with `pip`. If you have trouble, after installing `python3-pip` just run the `cd ~/Thunder && chmod +x setup && ./setup` again.

**Comment by AVRForVR** [comment]
![Screenshot 2024-03-23 6 17 07 PM](https://github.com/hadcl4/Thunder/assets/163577351/2667a879-7c17-41ed-aa20-3952d4bf48ef)
still not working

**Comment by hadcl4** [comment]
This is an error outside of Thunder based on how `guizero` still is missing, so you'll have to paste the output of `sudo pip3 install guizero` for me to be able to help.

**Comment by AVRForVR** [comment]
![image](https://github.com/hadcl4/Thunder/assets/163577351/67983dec-007c-4f2f-9480-82a32ef4f032)

**Comment by hadcl4** [comment]
Based off of that, maybe try `sudo pip3 install python3-guizero`? Don't remember ever seeing that error myself, so I might be wrong. If that doesn't work, I'll try thinking of something else to try.

**Comment by AVRForVR** [comment]
![Screenshot 2024-03-23 6 31 12 PM](https://github.com/hadcl4/Thunder/assets/163577351/16dce2d2-b5b6-4b8a-b5e5-53926a3b0a02)

**Comment by hadcl4** [comment]
Maybe instead `sudo apt install python3-guizero` and `sudo apt install python3-pil`?

**Comment by AVRForVR** [comment]
worked! thanks

**Comment by hadcl4** [comment]
You're welcome! Thanks for using Thunder!
